-- Run this in the Supabase SQL Editor to ensure your table structure is correct

CREATE TABLE IF NOT EXISTS public.proposals (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    client_name text,
    business_name text,
    proposal_number text,
    proposal_data jsonb
);

-- Enable Row Level Security (RLS) if you haven't already
ALTER TABLE public.proposals ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone to insert (since we have anon key)
-- NOTE: For production, you might want stricter policies.
CREATE POLICY "Enable insert for everyone" ON public.proposals FOR INSERT WITH CHECK (true);

-- Create a policy to allow selecting (optional, if you need to read back)
CREATE POLICY "Enable select for everyone" ON public.proposals FOR SELECT USING (true);
